# Generated by Django 6.0.7 on 2026-07-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '__first__'),
        ('patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('recommended_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diseases', to='doctors.specialization')),
                ('typical_symptoms', models.ManyToManyField(blank=True, help_text='Reference symptom set used by the diagnostic engine to score this disease.', related_name='typical_of_diseases', to='diagnostics.symptom')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(blank=True, help_text="Model's prediction confidence (0-1).", null=True)),
                ('other_symptoms', models.TextField(blank=True, default='', help_text='Additional free-text symptoms entered by the patient.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_requests', to='patients.patient')),
                ('recommended_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_recommendations', to='doctors.doctor')),
                ('predicted_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='diagnostics.disease')),
                ('symptoms', models.ManyToManyField(related_name='diagnosis_requests', to='diagnostics.symptom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
